### ISSUE TITLE
Bro had to drop the V2 so I wouldn't make fun of him

### ISSUE THREAD

**Issue by KDot227** [dynastyoak/Oak-Grabber-V2#1]
smh timmy wouldn't be proud

**Comment by KDot227** [comment]
Also remove the --icon None from the builder since that gives it more detections + build the bootloader + use key

**Comment by KDot227** [comment]
or be cool and use timmy's "python compiler"

**Comment by KDot227** [comment]
or instead of ps1 u can use the patent pending K.Dot powershell embed strat

**Comment by KDot227** [comment]
also ive addidix credit somewhere 💀 u stole half his shi

**Comment by KDot227** [comment]
nvm u did 💀 one line

**Comment by KDot227** [comment]
Also add file bloat I forgot what it's called if u want the code lmk

**Comment by dynastyoak** [comment]
what

**Comment by KDot227** [comment]
> what

read

**Comment by dynastyoak** [comment]
bro cap

**Comment by LocalSmail** [comment]
> Also add file bloat I forgot what it's called if u want the code lmk

he just like timmy frfr

**Comment by KDot227** [comment]
> > Also add file bloat I forgot what it's called if u want the code lmk
> 
> 
> 
> he just like timmy frfr

On me
